export const LAW_CODES: Record<string, [string, string][]> = {
"Title 1 – Crimes Against Persons": [
    ["§ 21-1-1", "Simple Assault (M)"],
    ["§ 21-1-2", "Aggravated Assault (F)"],
    ["§ 21-1-3", "Assault on a Peace Officer (F)"],
    ["§ 21-2-1", "Simple Battery (M)"],
    ["§ 21-2-2", "Aggravated Battery (F)"],
    ["§ 21-3-1", "Involuntary Manslaughter (F)"],
    ["§ 21-3-2", "Vehicular Manslaughter (F)"],
    ["§ 21-3-3", "Voluntary Manslaughter (F)"],
    ["§ 21-4-1", "Attempted Murder (F)"],
    ["§ 21-4-2", "Second Degree Murder (F)"],
    ["§ 21-4-3", "First Degree Murder (F)"],
    ["§ 21-4-4", "Capital Murder (F)"],
    ["§ 21-5-1", "Mutilation (F)"],
    ["§ 21-6-1", "Unlawful Restraint (M)"],
    ["§ 21-6-2", "Kidnapping (F)"],
    ["§ 21-6-3", "Hostage Taking (F)"],
    ["§ 21-7-1", "Criminal Threats I (M)"],
    ["§ 21-7-2", "Criminal Threats II (F)"],
    ["§ 21-7-3", "Threatening a Peace Officer (M)"],
    ["§ 21-7-4", "Aggravated Menacing (F)"],
    ["§ 21-7-5", "Hazing (M)"],
    ["§ 21-8-1", "Reckless Endangerment (M)"]
],
"Title 2 – Theft": [
    ["§ 22-1-1", "Petty Theft (M)"],
    ["§ 22-1-2", "Theft (F)"],
    ["§ 22-1-3", "Grand Theft (F)"],
    ["§ 22-1-4", "Grand Theft Auto (F)"],
    ["§ 22-2-1", "Burglary (F)"],
    ["§ 22-3-1", "Robbery (F)"],
    ["§ 22-3-2", "Bank Robbery (F)"],
    ["§ 22-3-3", "Robbery of Armored Transport (F)"],
    ["§ 22-4-1", "Possession of Stolen Property (M)"],
    ["§ 22-4-2", "Possession of a Stolen Vehicle (M)"]
],
"Title 3 – Fraud": [
    ["§ 23-1-1", "Extortion (F)"],
    ["§ 23-2-1", "Fraud (F)"],
    ["§ 23-3-1", "Impersonating (M)"],
    ["§ 23-4-1", "Forgery (M)"],
    ["§ 23-5-1", "Attempted Counterfeiting (F)"],
    ["§ 23-5-2", "Counterfeiting Currency (F)"],
    ["§ 23-5-3", "Sale of Counterfeit Currency (F)"]
],
"Title 4 – Property Crimes": [
    ["§ 24-1-1", "Trespassing (M)"],
    ["§ 24-1-2", "Breaking and Entering (F)"],
    ["§ 24-2-1", "Vandalism (M)"],
    ["§ 24-2-2", "Destruction of Property (F)"],
    ["§ 24-2-3", "Arson (F)"]
],
"Title 5 – Public Administration": [
    ["§ 25-1-1", "Bribery (F)"],
    ["§ 25-2-1", "Escape (F)"],
    ["§ 25-3-1", "Failure to Appear (M)"],
    ["§ 25-3-2", "Failure to Appear (F)"],
    ["§ 25-3-3", "Perjury (F)"],
    ["§ 25-3-4", "Violation of Court Order (M)"],
    ["§ 25-3-5", "Violation of Restraining Order (M)"],
    ["§ 25-3-6", "Violation of Probation (M)"],
    ["§ 25-3-7", "Contempt of Court (M)"],
    ["§ 25-4-1", "Conspiracy (M)"],
    ["§ 25-5-1", "Money Laundering (F)"],
    ["§ 25-6-1", "Racketeering (RICO) (F)"]
],
"Title 6 – Public Order": [
    ["§ 26-1-1", "Failure to Comply (M)"],
    ["§ 26-2-1", "Disorderly Conduct (M)"],
    ["§ 26-3-1", "Disturbing the Peace (M)"],
    ["§ 26-4-1", "False Reporting (M)"],
    ["§ 26-5-1", "Harassment (M)"],
    ["§ 26-6-1", "Obstruction (M)"],
    ["§ 26-6-2", "Obstruction of Law Enforcement (M)"],
    ["§ 26-6-3", "Hindering Apprehension (M)"],
    ["§ 26-7-1", "Inciting a Riot (F)"],
    ["§ 26-8-1", "Loitering (I)"],
    ["§ 26-9-1", "Tampering (M)"],
    ["§ 26-9-2", "Aiding and Abetting (M)"],
    ["§ 26-9-3", "Harboring a Fugitive (F)"],
    ["§ 26-10-1", "Animal Cruelty (M)"],
    ["§ 26-11-1", "Failure to ID (M)"],
    ["§ 26-12-1", "Abuse of Office (F)"],
    ["§ 26-13-1", "Vigilantism (F)"],
    ["§ 26-14-1", "Negligence (M)"],
    ["§ 26-15-1", "Criminal Conspiracy (F)"],
    ["§ 26-15-2", "Unlawful Assembly (M)"],
    ["§ 26-16-1", "General Indecency (I)"],
    ["§ 26-16-2", "Criminal Indecency (M)"]
],
"Title 7 – Public Health & Morals": [
    ["§ 27-1-1", "Possession w/ Intent to Distribute (F)"],
    ["§ 27-2-1", "Controlled Substance 1st Degree (F)"],
    ["§ 27-3-1", "Controlled Substance 2nd Degree (F)"],
    ["§ 27-4-1", "Controlled Substance 3rd Degree (M)"],
    ["§ 27-5-1", "Sale of Controlled Substance (F)"],
    ["§ 27-6-1", "Public Intoxication (M)"],
    ["§ 27-7-1", "Littering (I)"],
    ["§ 27-8-1", "Unlicensed Medical Practice (F)"],
    ["§ 27-9-1", "Inhumane Detainment (F)"]
],
"Title 8 – Public Safety": [
    ["§ 28-1-1", "Criminal Possession of Firearm (F)"],
    ["§ 28-1-2", "Unlicensed Firearm (M)"],
    ["§ 28-1-3", "Illegal Firearm (F)"],
    ["§ 28-2-1", "Criminal Sale of Firearm (F)"],
    ["§ 28-2-2", "Black Market (F)"],
    ["§ 28-3-1", "Criminal Use of Firearm (F)"],
    ["§ 28-3-2", "Criminal Use of Weapon (F)"],
    ["§ 28-3-3", "Unlawful Discharge (F)"],
    ["§ 28-4-1", "Brandishing (M)"],
    ["§ 28-5-1", "Resisting Arrest (M)"],
    ["§ 28-6-1", "Jaywalking (I)"],
    ["§ 28-6-2", "Impeding Traffic (I)"],
    ["§ 28-7-1", "Possession of Stolen Firearm (F)"],
    ["§ 28-8-1", "Unlawful Carrying (M)"],
    ["§ 28-8-2", "Firearm in No-Weapon Zone (M)"],
    ["§ 28-8-3", "Firearm During Crime (F)"],
    ["§ 28-9-1", "Explosive Device (F)"],
    ["§ 28-9-2", "Throwing Missiles (F)"]
],
"Title 9A – Driving Behavior": [
    ["§ 29-1-1", "3rd Degree Speeding (I)"],
    ["§ 29-1-2", "2nd Degree Speeding (I)"],
    ["§ 29-1-3", "1st Degree Speeding (F)"],
    ["§ 29-1-4", "Negligent Driving (M)"],
    ["§ 29-1-5", "Reckless Driving (F)"],
    ["§ 29-1-6", "Exhibition of Speed (M)"],
    ["§ 29-1-7", "Hit and Run (F)"],
    ["§ 29-1-8", "Drag Racing (F)"],
    ["§ 29-1-9", "Felony Speeding (F)"],
    ["§ 29-3-5", "Evading (F)"]
],
"Title 9B – Licensing & Registration": [
    ["§ 29-8-1", "Suspended License (M)"],
    ["§ 29-8-2", "No License (M)"],
    ["§ 29-9-1", "Expired Registration (I)"],
    ["§ 29-9-2", "Unregistered Vehicle (M)"],
    ["§ 29-10-1", "No Insurance (I)"]
],
"Title 9C – Traffic Control & Equipment": [
    ["§ 29-2-1", "Distracted Driving (I)"],
    ["§ 29-2-2", "Open Container (M)"],
    ["§ 29-2-3", "DWI (M)"],
    ["§ 29-2-4", "DUI (F)"],
    ["§ 29-3-1", "Fail Yield Emergency (I)"],
    ["§ 29-3-2", "Move Over Law (I)"],
    ["§ 29-4-1", "Disobey Traffic Control (I)"],
    ["§ 29-5-1", "No Turn Signal (I)"],
    ["§ 29-5-2", "No Headlights (I)"]
],
"Title 9D – Parking & Minor Infractions": [
    ["§ 29-11-1", "No Seatbelt (I)"],
    ["§ 29-12-1", "Illegal Parking (I)"],
    ["§ 29-12-5", "Handicap Parking (I)"],
    ["§ 29-13-1", "Emergency Equipment (M)"],
    ["§ 29-13-2", "Unlawful Emergency Lights (I)"]
],
"Title 10 – Juvenile Offenses": [
    ["§ 30-1-1", "Curfew Violation (I)"],
    ["§ 30-1-2", "Runaway (I)"],
    ["§ 30-2-1", "Truancy (I)"],
    ["§ 30-3-1", "Minor in Possession (M)"],
    ["§ 30-3-2", "Minor Purchasing Alcohol (M)"],
    ["§ 30-4-1", "Juvenile Disorderly Conduct (M)"],
    ["§ 30-5-1", "Juvenile Assault (M)"]
],
"Title 11 – Business & Financial Crimes": [
    ["§ 31-1-1", "Operating Without License (M)"],
    ["§ 31-1-2", "Unlawful Business Practices (M)"],
    ["§ 31-2-1", "Tax Evasion (F)"],
    ["§ 31-3-1", "Insider Trading (F)"],
    ["§ 31-4-1", "Price Fixing (F)"],
    ["§ 31-5-1", "Corporate Fraud (F)"],
    ["§ 31-6-1", "Embezzlement (F)"],
    ["§ 31-7-1", "Ponzi Scheme (F)"]
],
"Title 12 – Environmental & Wildlife": [
    ["§ 32-1-1", "Illegal Dumping (M)"],
    ["§ 32-1-2", "Hazardous Waste Disposal (F)"],
    ["§ 32-2-1", "Poaching (M)"],
    ["§ 32-2-2", "Endangered Species Violation (F)"],
    ["§ 32-3-1", "Pollution of Waterways (F)"],
    ["§ 32-4-1", "Illegal Burning (M)"],
    ["§ 32-5-1", "Destruction of Protected Land (F)"]
],
"Title 13 – Military & Government Facilities": [
    ["§ 33-1-1", "Unauthorized Base Entry (F)"],
    ["§ 33-1-2", "Espionage (F)"],
    ["§ 33-2-1", "Sabotage (F)"],
    ["§ 33-3-1", "Treason (F)"],
    ["§ 33-4-1", "Interference with Military Ops (F)"],
    ["§ 33-5-1", "Theft of Government Property (F)"],
    ["§ 33-6-1", "Damage to Government Facility (F)"]
]
};
